package-lock.json, package.json
@contentstack/app-cli : 1.0.3 -> 1.0.4
=> version bump 1.0.4

package-lock.json, package.json, src/app-cli-base-coomand.ts, src/base-command.ts, src/commands/app/create.ts, src/commands/app/delete.ts, src/commands/app/get.ts, src/commands/app/index.ts, src/commands/app/install.ts, src/commands/app/uninstall.ts, src/commands/app/update.ts, src/messages/index.ts, src/util/common-utils.ts, src/util/inquirer.ts
=> development to staging

LICENSE, README.md, package-lock.json, package.json, src/app-cli-base-coomand.ts, src/base-command.ts, src/commands/app/create.ts, src/commands/app/delete.ts, src/commands/app/get.ts, src/commands/app/index.ts, src/commands/app/install.ts, src/commands/app/uninstall.ts, src/commands/app/update.ts, src/messages/index.ts, src/util/common-utils.ts, src/util/inquirer.ts
=> Staging to Main

package-lock.json, package.json, src/config/index.ts
Fix for  - CS-43613
- Updated app boilerplate release URL to pull the latest changes 
- Updated command and utility package versions to latest available
- Package version bumped
=> Used latest boilerplate code pull strategy

package-lock.json, package.json, src/config/index.ts
version bump:
contentstack/apps-cli: 1.0.5 -> 1.0.6
=> CS-43644- added gcp developerhubUrls in config 

package-lock.json, package.json, src/util/inquirer.ts
version bump:
@contentstack/apps-cli: 1.0.6 -> 1.0.7
=> CS-43661-added developerhub url from cma, and version bump

src/commands/app/reinstall.ts
=> fix: update manifest uid for reinstalling old and new apps created

test/unit/commands/app/reinstall.test.ts
=> dx-542 reinstall command unit test

.gitignore
=> Staging to development

src/commands/app/delete.ts, src/commands/app/install.ts, src/commands/app/reinstall.ts, src/commands/app/uninstall.ts, src/util/common-utils.ts
=> feat: replaced delete and uninstall command api calls

src/commands/app/deploy.ts, src/messages/index.ts, src/types/app.ts, src/util/inquirer.ts
=> fix: deploy command

package-lock.json, package.json, test/unit/commands/app/deploy.test.ts, test/unit/mock/common.mock.json
=> dx-543 | deploy command unit tests

README.md, package-lock.json, package.json, src/messages/index.ts
=> fix: sre issues

README.md, package-lock.json, package.json
=> Fix: Getting Cannot find module @apollo/client/core with latest version

README.md, src/commands/app/create.ts, src/config/index.ts, src/messages/index.ts, src/util/common-utils.ts, src/util/inquirer.ts
updated with a boilerplates flag and added example
=> updated with a flag and added example

src/commands/app/deploy.ts, src/commands/app/reinstall.ts, src/util/common-utils.ts
- updated reinstall and deploy with marketplace calls
- version bump to be made
=> updated reinstall and deploy with marketplace calls

README.md, src/messages/index.ts, src/util/inquirer.ts
updated flag and prompt description for boilerplate flag
=> updated flag and prompt description

README.md, package-lock.json, package.json, src/base-command.ts, src/commands/app/create.ts, src/commands/app/delete.ts, src/commands/app/deploy.ts, src/commands/app/get.ts, src/commands/app/index.ts, src/commands/app/install.ts, src/commands/app/reinstall.ts, src/commands/app/uninstall.ts, src/commands/app/update.ts, src/util/inquirer.ts
=> fix: handle undefined issue & org flag missing in help command

README.md, package-lock.json, package.json, src/commands/app/deploy.ts, src/util/inquirer.ts
=> fix: deploy command launch base url issue

README.md, package-lock.json, src/commands/app/install.ts, src/commands/app/reinstall.ts
- version bump to be done if this is not going to release of 28th
- all tests passing
- fixed receiving eexit after encountering error
=> dx | 1157 | encountering eexit after receiving error

src/base-command.ts
- replace get developer hub url method
- version bump to be made
=> dx | 1170 replace get developer hub url method

examples/create-launch-project.json, package-lock.json, package.json, src/commands/app/deploy.ts
Added version bump, 1.3.4 -> 1.4.0
=> [DX-1158], added support for the new launch flags

.eslintrc, .github/workflows/unit-test.yml, README.md, package-lock.json, package.json, test/unit/commands/app/create.test.ts, test/unit/commands/app/delete.test.ts, test/unit/commands/app/deploy.test.ts, test/unit/commands/app/get.test.ts, test/unit/commands/app/install.test.ts, test/unit/commands/app/reinstall.test.ts, test/unit/commands/app/uninstall.test.ts, test/unit/commands/app/update.test.ts, test/unit/helpers/auth-stub-helper.ts
=> update testcases and add GH pipeline for it

README.md, package-lock.json, package.json
reverting version as no release is required, we only updated the test cases and no business logic was changed.
=> revert version
